### PR TITLE
check gtfs version

### PR DESCRIPTION
**Pull request by xlqian**

### CODE REVIEW

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by xlqian** [comment]
Jekins, test this please!

**Comment by xlqian** [comment]
Jenkins, test this please!

**Comment by pbougue** [comment]
Jenkins, test this please!

**Comment by pbougue** [comment]
Jenkins, test this please.

**Comment by xlqian** [comment]
Jenkins, test this please!

**Pull request merged**
