### PR TITLE
Message handling

### PR DESCRIPTION
**Pull request by antoine-de**
handle cause at stoptimeupdate level

### CODE REVIEW

**Comment by Hoshiyo** [comment]
Jenkins, test this please

**Comment by Hoshiyo** [comment]
Jenkins, test this please

**Comment by Hoshiyo** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by antoine-de** [comment]
Jenkins, test this please

**Comment by pbougue** [comment]
Ok for me

**Comment by antoine-de** [comment]
Jenkins, test this please

**Pull request merged**
