### PR TITLE
ire: support parity

### PR DESCRIPTION
**Pull request by TeXitoi**
http://jira.canaltp.fr/browse/NAVP-343

### CODE REVIEW

**Comment by xlqian** [comment]
ok for me

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Comment by TeXitoi** [comment]
Jenkins, test this please

**Pull request merged**
